### ISSUE TITLE
possible problem with  sub_class and prob_sub_class 

### ISSUE THREAD

**Issue by schwidom** [rzese/trill#2]
Hi, I left you a question in the swi prolog forum:

https://swi-prolog.discourse.group/t/pack-trill-problem-with-sub-class-and-prob-sub-class/5229

And another question: what means kb? It appears in your documentation but I found no translation.

Thanks in advance,
Frank.

**Comment by rzese** [comment]
Dear Frank,
yes, there was a small bug. It should now work correctly.

Regarding the acronym KB, it stands for Knowledge Base. I have updated the documentation.

Please let me know if you find any other problems or if you experience anything strange. I will be very happy to fix it.

Kind regards
Riccardo

**Comment by schwidom** [comment]
Thanks
