### ISSUE TITLE
I am pretty sure this is also a bug:

### ISSUE THREAD

**Issue by schwidom** [rzese/trill#3]
Hi, some queries take a long time and then endup in a stacktrace, see here:

https://swi-prolog.discourse.group/t/stacktraces-in-package-trill/5247

Thanks in advance,
Frank.

**Comment by rzese** [comment]
It was due to wrong stopping criteria when traversing the tableau.
Now it should work properly.

Thank you again for your interest and help.

Riccardo

**Comment by schwidom** [comment]
Thanks. Btw. I left a question on discourse.

Regards,
Frank.
